export const testUsrPosts = [
    {
        id: 1,
        first_name: 'Marcus',
        last_name: 'Bennett',
        user_name: 'mbennett_dev',
        is_admin: true,
        post_title: 'My Morning Coffee Ritual',
        post_content:
            'There is nothing quite like the smell of freshly ground beans at 6:00 AM. It’s the only way I can actually start my coding sessions with a clear head. Usually, I go for a light roast with some citrus notes.',
    },
    {
        id: 2,
        first_name: 'Elena',
        last_name: 'Rodriguez',
        user_name: 'elena_travels',
        is_admin: false,
        post_title: 'The Comprehensive Guide to Hidden Gems in Madrid',
        post_content:
            "If you ever find yourself in Madrid, skip the main plaza and head straight to the narrow alleys of La Latina for the best tapas you've ever had in your life. But it's not just about the food. You need to visit the rooftop bars near Templo de Debod at sunset. The way the light hits the ancient stone while the city starts to glow below you is something you won't find in any standard guidebook. Also, don't forget that most of the best museums are free on certain evenings—check the local schedules before you buy a ticket!",
    },
    {
        id: 3,
        first_name: 'Jordan',
        last_name: 'Smith',
        user_name: 'jsmith99',
        is_admin: false,
        post_title: 'New Keyboard',
        post_content: 'Just switched to a mechanical keyboard. My fingers are still adjusting.',
    },
    {
        id: 4,
        first_name: 'Sarah',
        last_name: 'Jenkins',
        user_name: 'sarah_j_cooks',
        is_admin: false,
        post_title: 'Easy Sourdough',
        post_content:
            "I finally mastered the art of the sourdough starter! It took three weeks of feeding and a lot of patience, but the crust on today's loaf was absolutely perfect. The crumb was airy and the tang was just right.",
    },
    {
        id: 5,
        first_name: 'David',
        last_name: 'Kim',
        user_name: 'dk_tech',
        is_admin: true,
        post_title: 'Why VS Code Extensions are the Secret to Productivity',
        post_content:
            "If you aren't using 'Prettier' and 'ESLint' together, you are making your life much harder than it needs to be. Clean code is happy code. I also highly recommend 'Bracket Pair Colorizer' and 'GitLens' for anyone working in a large team. Being able to see who wrote which line of code directly in the editor saves so much time during debugging. It's these small optimizations that add up to hours of saved time every single month.",
    },
    {
        id: 6,
        first_name: 'Chloe',
        last_name: 'Vance',
        user_name: 'chloe_v',
        is_admin: false,
        post_title: 'Weekend Hiking',
        post_content:
            'The trail up to the peak was steeper than I expected, but the view of the valley below made every single step worth the effort. Saw a hawk too!',
    },
    {
        id: 7,
        first_name: 'Liam',
        last_name: "O'Connor",
        user_name: 'liam_oc',
        is_admin: false,
        post_title: 'Vinyl Collection',
        post_content: "Just added a first-pressing of 'Rumours' to my collection.",
    },
    {
        id: 8,
        first_name: 'Maya',
        last_name: 'Patel',
        user_name: 'maya_p_designs',
        is_admin: false,
        post_title: 'A Deep Dive into Inclusive UI Design and Why It Matters for Everyone',
        post_content:
            "Always prioritize accessibility. A beautiful design is useless if people with visual impairments can't navigate your interface effectively. This means checking your color contrast ratios, ensuring your site is keyboard-navigable, and using semantic HTML tags properly. We often get caught up in the latest aesthetic trends—like glassmorphism or neumorphism—but if those trends create barriers for our users, we have failed as designers. Inclusion isn't a feature; it's a fundamental requirement of the modern web.",
    },
    {
        id: 9,
        first_name: 'Ethan',
        last_name: 'Hunt',
        user_name: 'ethan_h',
        is_admin: false,
        post_title: 'Workout Routine',
        post_content:
            'Consistency is more important than intensity. Even if you only have fifteen minutes, moving your body every day makes a massive difference.',
    },
    {
        id: 10,
        first_name: 'Sophia',
        last_name: 'Gomez',
        user_name: 'sophia_g',
        is_admin: true,
        post_title: 'Deep Diving into React Hooks',
        post_content:
            'Understanding the dependency array in useEffect is crucial if you want to avoid those pesky infinite loops. I spent three hours today debugging a component that kept re-rendering because I passed an object directly into the array instead of a specific primitive value. Learn from my mistakes: always memoize your objects or just destructure the properties you actually need to watch! ',
    },
    // {
    //     id: 11,
    //     first_name: 'Noah',
    //     last_name: 'Fisher',
    //     user_name: 'nfisher_88',
    //     is_admin: false,
    //     post_title: 'Urban Gardening',
    //     post_content: 'My balcony tomatoes are finally turning red!',
    // },
    // {
    //     id: 12,
    //     first_name: 'Isabella',
    //     last_name: 'Rossi',
    //     user_name: 'bella_rossi',
    //     is_admin: false,
    //     post_title: 'The Art of the Perfect Italian Espresso',
    //     post_content:
    //         "There’s a specific technique to pulling a perfect shot of espresso. It’s all about the pressure, the grind, and the love you put into the machine. You have to listen to the pump; the sound changes when the extraction is just right. If it flows too fast, your grind is too coarse. Too slow? You've packed it too tight. It's a delicate balance that takes years to master, but once you taste that perfect crema, there is no going back to instant coffee.",
    // },
    // {
    //     id: 13,
    //     first_name: 'Lucas',
    //     last_name: 'Meyer',
    //     user_name: 'lmeyer_fin',
    //     is_admin: false,
    //     post_title: 'Budgeting 101',
    //     post_content:
    //         'Start by tracking every single cent for a month. You would be surprised how much money disappears into small subscriptions.',
    // },
    // {
    //     id: 14,
    //     first_name: 'Mia',
    //     last_name: 'Wong',
    //     user_name: 'mia_w_art',
    //     is_admin: false,
    //     post_title: 'Watercolor Painting',
    //     post_content:
    //         "Working with watercolors is a lesson in letting go of control. You have to let the water and the pigment do their own thing sometimes. It's incredibly therapeutic to just watch the colors bleed together on the paper without a specific plan in mind.",
    // },
    // {
    //     id: 15,
    //     first_name: 'Logan',
    //     last_name: 'Brooks',
    //     user_name: 'lbrooks_cam',
    //     is_admin: false,
    //     post_title: 'Golden Hour Photography',
    //     post_content:
    //         'The twenty minutes before sunset provide the most magical light. Everything turns gold, and the shadows get long and dramatic.',
    // },
    // {
    //     id: 16,
    //     first_name: 'Ava',
    //     last_name: 'Thompson',
    //     user_name: 'ava_t_reads',
    //     is_admin: false,
    //     post_title: 'Book Review: Why Dune is Still the King of Sci-Fi',
    //     post_content:
    //         "I finally finished reading Dune. The world-building is incredibly dense, but the political intrigue kept me turning pages late into the night. It's amazing how a book written in the 60s can still feel so relevant today. The themes of ecology, religion, and the dangers of a 'messiah' figure are handled with such nuance. If you've only seen the movies, you are missing out on about 70% of the internal monologue that makes Paul such a fascinating, and at times terrifying, protagonist.",
    // },
    // {
    //     id: 17,
    //     first_name: 'James',
    //     last_name: 'Carter',
    //     user_name: 'j_carter_92',
    //     is_admin: false,
    //     post_title: 'Mechanical Watches',
    //     post_content:
    //         "There's something poetic about a machine that keeps time without a battery. Watching the balance wheel beat is like seeing a heartbeat.",
    // },
    // {
    //     id: 18,
    //     first_name: 'Emma',
    //     last_name: 'Davis',
    //     user_name: 'emma_d_writes',
    //     is_admin: false,
    //     post_title: "Writer's Block",
    //     post_content: "The best way to beat writer's block is to write poorly. Just get the words out.",
    // },
    // {
    //     id: 19,
    //     first_name: 'Oliver',
    //     last_name: 'Zhang',
    //     user_name: 'ozhang_dev',
    //     is_admin: true,
    //     post_title: 'Docker for Beginners',
    //     post_content:
    //         "Containerization changed my workflow. No more 'it works on my machine' excuses. Everything is isolated and reproducible now. Once you get the hang of writing a Dockerfile, you'll wonder how you ever managed without it.",
    // },
    // {
    //     id: 20,
    //     first_name: 'Charlotte',
    //     last_name: 'King',
    //     user_name: 'char_king',
    //     is_admin: false,
    //     post_title: 'Yoga for Posture',
    //     post_content:
    //         'Sitting at a desk all day was wrecking my back. Ten minutes of cat-cow and downward dog every morning has completely changed my life. My tension headaches have almost vanished entirely since I started this routine.',
    // },
    // {
    //     id: 21,
    //     first_name: 'Benjamin',
    //     last_name: 'Lee',
    //     user_name: 'ben_lee_music',
    //     is_admin: false,
    //     post_title: 'Jazz Piano',
    //     post_content:
    //         "Jazz is all about the notes you don't play. 2-5-1 progressions are the foundation of everything.",
    // },
    // {
    //     id: 22,
    //     first_name: 'Amelia',
    //     last_name: 'Scott',
    //     user_name: 'amelia_s',
    //     is_admin: false,
    //     post_title: 'Sustainable Fashion',
    //     post_content:
    //         "I've committed to only buying second-hand clothes this year. It's better for the planet and the finds are way more unique.",
    // },
    // {
    //     id: 23,
    //     first_name: 'Henry',
    //     last_name: 'White',
    //     user_name: 'hwhite_chess',
    //     is_admin: false,
    //     post_title: 'The Sicilian Defense: Why It’s the Most Complex Chess Opening',
    //     post_content:
    //         "I've been playing the Sicilian Defense lately. It's sharp and complicated, which usually leads to some very interesting tactical battles. Unlike the symmetrical King's Pawn openings, the Sicilian immediately creates an imbalance. Black is playing for the win from move one, not just a draw. However, it requires a massive amount of theory knowledge. One wrong move in the Najdorf variation and the game can be over in twenty moves. It’s stressful, but when your preparation pays off, it feels incredible.",
    // },
    // {
    //     id: 24,
    //     first_name: 'Harper',
    //     last_name: 'Young',
    //     user_name: 'harper_y',
    //     is_admin: false,
    //     post_title: 'Meditation',
    //     post_content: 'I started using a guided meditation app. It helps.',
    // },
    // {
    //     id: 25,
    //     first_name: 'Sebastian',
    //     last_name: 'Hill',
    //     user_name: 'seb_hill_90',
    //     is_admin: false,
    //     post_title: 'Cycling in the Rain',
    //     post_content:
    //         'There is no such thing as bad weather, only bad clothing. With the right waterproof gear, a rainy bike ride can actually be quite peaceful.',
    // },
    // {
    //     id: 26,
    //     first_name: 'Evelyn',
    //     last_name: 'Baker',
    //     user_name: 'ebaker_bakes',
    //     is_admin: false,
    //     post_title: 'The Secret to Perfect Chocolate Chip Cookies is Patience',
    //     post_content:
    //         "The secret is browning the butter first. It adds a nutty depth that makes people wonder why your cookies taste so much better than theirs. But the real trick? Let the dough rest in the fridge for at least 24 hours. This allows the flour to fully hydrate and the sugars to break down, resulting in a deeper, toffee-like flavor and a better texture. If you bake them right away, you're missing out on the best version of your own recipe.",
    // },
    // {
    //     id: 27,
    //     first_name: 'Jackson',
    //     last_name: 'Adams',
    //     user_name: 'jax_adams',
    //     is_admin: false,
    //     post_title: 'Desktop Setup',
    //     post_content: 'Just added an ultrawide monitor. Game changer for productivity.',
    // },
    // {
    //     id: 28,
    //     first_name: 'Scarlett',
    //     last_name: 'Green',
    //     user_name: 'scarlett_g',
    //     is_admin: false,
    //     post_title: 'Minimalism',
    //     post_content:
    //         'Owning less stuff means having more time and energy for experiences. Getting rid of my old clutter felt like a weight being lifted off my shoulders.',
    // },
    // {
    //     id: 29,
    //     first_name: 'Daniel',
    //     last_name: 'Nelson',
    //     user_name: 'dan_nelson_ai',
    //     is_admin: true,
    //     post_title: 'The Future of AI and How It Will Reshape the Creative Industry',
    //     post_content:
    //         "Large language models are just the beginning. The real shift will happen when these tools are integrated seamlessly into our creative workflows. We are moving from a world where we 'manually' create to a world where we 'curate' and 'direct' AI-generated outputs. This doesn't mean artists and writers will disappear, but their roles will evolve. Those who learn to collaborate with these systems will find themselves with superpowers, while those who resist may find the landscape increasingly difficult to navigate. It's an exciting, if slightly terrifying, time to be a creator.",
    // },
    // {
    //     id: 30,
    //     first_name: 'Lily',
    //     last_name: 'Hall',
    //     user_name: 'lily_h_plants',
    //     is_admin: false,
    //     post_title: 'Stop Overwatering!',
    //     post_content: 'Most houseplant deaths are caused by kindness. Let them dry out!',
    // },
    // {
    //     id: 31,
    //     first_name: 'Alexander',
    //     last_name: 'Perez',
    //     user_name: 'alex_p_running',
    //     is_admin: false,
    //     post_title: 'Half-Marathon Training',
    //     post_content:
    //         'Running my first half-marathon next month. The long runs on Saturdays are brutal, but seeing my pace improve every week is keeping me motivated.',
    // },
    // {
    //     id: 32,
    //     first_name: 'Grace',
    //     last_name: 'Campbell',
    //     user_name: 'grace_c_codes',
    //     is_admin: false,
    //     post_title: 'Python Tips',
    //     post_content: 'List comprehensions are one of the most Pythonic ways to write clean, readable code. Use them!',
    // },
    // {
    //     id: 33,
    //     first_name: 'Matthew',
    //     last_name: 'Parker',
    //     user_name: 'mparker_99',
    //     is_admin: false,
    //     post_title: 'Coffee Brewing',
    //     post_content: 'I switched from a standard drip machine to a Chemex. The flavor profile is so much cleaner.',
    // },
    // {
    //     id: 34,
    //     first_name: 'Victoria',
    //     last_name: 'Evans',
    //     user_name: 'vicky_e_style',
    //     is_admin: false,
    //     post_title: 'My Journey Toward a 30-Item Capsule Wardrobe',
    //     post_content:
    //         "Creating a capsule wardrobe has made my mornings so much easier. I have fewer choices, but everything I own fits me well and I love wearing it. I used to spend twenty minutes every morning staring at a full closet crying that I had nothing to wear. Now, I can get dressed in five minutes flat and I feel more confident than ever. It's about quality over quantity—buying one $100 sweater that lasts five years instead of five $20 sweaters that fall apart after three washes.",
    // },
    // {
    //     id: 35,
    //     first_name: 'Joseph',
    //     last_name: 'Edwards',
    //     user_name: 'joe_ed_gaming',
    //     is_admin: false,
    //     post_title: 'Retro Gaming',
    //     post_content: 'Found my old SNES. Chrono Trigger still holds up.',
    // },
    // {
    //     id: 36,
    //     first_name: 'Zoe',
    //     last_name: 'Collins',
    //     user_name: 'zoe_c_dev',
    //     is_admin: true,
    //     post_title: 'TypeScript is Essential',
    //     post_content:
    //         "I used to think types were just extra work, but now I can't imagine writing a large-scale JavaScript application without the safety of TypeScript. It catches so many bugs before the code even runs.",
    // },
    // {
    //     id: 37,
    //     first_name: 'Andrew',
    //     last_name: 'Stewart',
    //     user_name: 'astewart_film',
    //     is_admin: false,
    //     post_title: 'Cinematography',
    //     post_content: "The rule of thirds is a great starting point, but don't be afraid to break it.",
    // },
    // {
    //     id: 38,
    //     first_name: 'Penelope',
    //     last_name: 'Morris',
    //     user_name: 'penny_m_travel',
    //     is_admin: false,
    //     post_title: 'Solo Travel in Japan: A Solo Female Traveler’s Perspective',
    //     post_content:
    //         "Japan is the perfect country for solo travelers. It’s safe, the public transport is flawless, and eating alone in a ramen shop is totally normal. I spent two weeks traveling from Tokyo to Osaka and never once felt uncomfortable. The level of respect for personal space is incredible. If you're nervous about your first solo trip, Japan should be at the top of your list. The only downside is the language barrier in smaller towns, but a translation app and some polite bowing go a very long way!",
    // },
    // {
    //     id: 39,
    //     first_name: 'Christopher',
    //     last_name: 'Rogers',
    //     user_name: 'crogers_diy',
    //     is_admin: false,
    //     post_title: 'Woodworking Project',
    //     post_content: 'I built a walnut coffee table this weekend. Sanding took forever, but the result is beautiful.',
    // },
    // {
    //     id: 40,
    //     first_name: 'Hannah',
    //     last_name: 'Reed',
    //     user_name: 'hannah_r_yoga',
    //     is_admin: false,
    //     post_title: 'Mindfulness',
    //     post_content: 'Taking just five deep breaths before a meeting can completely change your energy. Try it today.',
    // },
];
export const testUsrCmts = [
    {
        id: 1,
        comment:
            "AeroPress is actually my favorite for morning rituals. It's so much faster to clean up than a Chemex!",
        date: '2026-02-15',
        first_name: 'Sam',
        last_name: 'Rivers',
        user_name: 's_rivers_coffee',
        is_admin: true,
        post_id: 1,
        post_title: 'My Morning Coffee Ritual',
    },
    {
        id: 2,
        comment:
            'I went to La Latina last year because of a similar recommendation and honestly, the patatas bravas changed my life. If you go back, you have to try the little place with the blue door near the church!',
        date: '2026-03-01',
        first_name: 'Julia',
        last_name: 'Chen',
        user_name: 'jules_explorer',
        is_admin: false,
        post_id: 2,
        post_title: 'The Comprehensive Guide to Hidden Gems in Madrid',
    },
    {
        id: 3,
        comment:
            'Brown switches are the best middle ground. All the tactile feel without waking up the entire house at 2 AM.',
        date: '2026-01-20',
        first_name: 'Mike',
        last_name: 'Wazowski',
        user_name: 'mike_tech_tips',
        is_admin: true,
        post_id: 3,
        post_title: 'New Keyboard',
    },
    {
        id: 4,
        comment:
            "My starter keeps smelling like vinegar. Is that normal or did I kill it? I've been feeding it 1:1:1 ratios but the kitchen is a bit cold this time of year.",
        date: '2026-03-05',
        first_name: 'Tom',
        last_name: 'Baker',
        user_name: 'tommy_bakes',
        is_admin: false,
        post_id: 4,
        post_title: 'Easy Sourdough',
    },
    {
        id: 5,
        comment:
            "GitLens is a lifesaver when you're trying to figure out who broke the build on a Friday afternoon lol.",
        date: '2026-02-10',
        first_name: 'Sarah',
        last_name: 'Connor',
        user_name: 's_connor_dev',
        is_admin: false,
        post_id: 5,
        post_title: 'Why VS Code Extensions are the Secret to Productivity',
    },
    {
        id: 6,
        comment: 'Great views!',
        date: '2026-03-10',
        first_name: 'Ben',
        last_name: 'Hiker',
        user_name: 'benny_h',
        is_admin: false,
        post_id: 6,
        post_title: 'Weekend Hiking',
    },
    {
        id: 7,
        comment: 'Fleetwood Mac is essential listening on vinyl. The production value on that album is insane.',
        date: '2025-12-12',
        first_name: 'Record',
        last_name: 'Rick',
        user_name: 'vinyl_ricky',
        is_admin: false,
        post_id: 7,
        post_title: 'Vinyl Collection',
    },
    {
        id: 8,
        comment:
            "I really appreciate you mentioning semantic HTML. So many people just use divs for everything and it makes screen readers completely useless. It's not just about the look, it's about the structure. I've been trying to advocate for this at my current company, but the senior devs are stuck in their ways. This post is a great resource to show them!",
        date: '2026-02-28',
        first_name: 'Alice',
        last_name: 'Wonder',
        user_name: 'alice_ui',
        is_admin: true,
        post_id: 8,
        post_title: 'A Deep Dive into Inclusive UI Design',
    },
    {
        id: 9,
        comment: 'I needed to hear this today. Struggling with motivation lately.',
        date: '2026-03-09',
        first_name: 'Kevin',
        last_name: 'Strong',
        user_name: 'kev_fitness',
        is_admin: false,
        post_id: 9,
        post_title: 'Workout Routine',
    },
    {
        id: 10,
        comment:
            "Wait, so if I use an object in the dependency array, I should wrap it in useMemo first? I think that's where my memory leak is coming from. Thanks for the tip!",
        date: '2026-01-15',
        first_name: 'Dev',
        last_name: 'Dan',
        user_name: 'dan_codes',
        is_admin: false,
        post_id: 10,
        post_title: 'Deep Diving into React Hooks',
    },
    {
        id: 11,
        comment: 'Yum!',
        date: '2026-03-11',
        first_name: 'Lily',
        last_name: 'Green',
        user_name: 'lily_g',
        is_admin: false,
        post_id: 11,
        post_title: 'Urban Gardening',
    },
    {
        id: 12,
        comment:
            "The pressure really is everything. If you don't have a good tamper, you're never going to get that consistent shot. I spent way too much on my espresso machine but honestly, the joy of a perfect morning latte is worth every penny.",
        date: '2026-02-20',
        first_name: 'Coffee',
        last_name: 'Chris',
        user_name: 'chris_espresso',
        is_admin: false,
        post_id: 12,
        post_title: 'The Art of the Perfect Italian Espresso',
    },
    {
        id: 13,
        comment: "Subscriptions are the silent killer. I found three $15/month services I hadn't used in a year!",
        date: '2026-03-02',
        first_name: 'Penny',
        last_name: 'Saver',
        user_name: 'penny_wise',
        is_admin: false,
        post_id: 13,
        post_title: 'Budgeting 101',
    },
    {
        id: 14,
        comment:
            "I struggle with 'letting go' too. I always try to over-fix the mistakes and end up with muddy colors. Great advice.",
        date: '2026-02-25',
        first_name: 'Art',
        last_name: 'Annie',
        user_name: 'annie_paint',
        is_admin: false,
        post_id: 14,
        post_title: 'Watercolor Painting',
    },
    {
        id: 15,
        comment: 'What lens did you use for this? The bokeh is beautiful.',
        date: '2026-03-07',
        first_name: 'Flash',
        last_name: 'Gordon',
        user_name: 'flash_pix',
        is_admin: false,
        post_id: 15,
        post_title: 'Golden Hour Photography',
    },
    {
        id: 16,
        comment:
            "I've tried reading Dune three times and I always get stuck around the part where they meet the Fremen. The terminology is just so overwhelming. Does it get easier to follow in the second half of the book? I really want to finish it before the next movie comes out but I feel like I need a dictionary just to understand the conversations.",
        date: '2026-01-30',
        first_name: 'Brian',
        last_name: 'Reader',
        user_name: 'brian_books',
        is_admin: false,
        post_id: 16,
        post_title: 'Book Review: Why Dune is Still the King of Sci-Fi',
    },
    {
        id: 17,
        comment: 'Grand Seiko is doing some incredible things with their Spring Drive movements lately.',
        date: '2026-02-12',
        first_name: 'Watch',
        last_name: 'Will',
        user_name: 'will_time',
        is_admin: false,
        post_id: 17,
        post_title: 'Mechanical Watches',
    },
    {
        id: 18,
        comment: 'Amen to that. Just keep the cursor moving.',
        date: '2026-03-08',
        first_name: 'Writers',
        last_name: 'Block',
        user_name: 'write_on',
        is_admin: false,
        post_id: 18,
        post_title: "Writer's Block",
    },
    {
        id: 19,
        comment: 'docker-compose is where the real magic happens for local dev environments.',
        date: '2026-02-05',
        first_name: 'Dev',
        last_name: 'Ops',
        user_name: 'devops_eric',
        is_admin: true,
        post_id: 19,
        post_title: 'Docker for Beginners',
    },
    {
        id: 20,
        comment:
            "My lower back has been killing me lately. I'm going to try the cat-cow stretch tomorrow morning. Do you have any other suggestions for hip flexor tightness? That seems to be my biggest issue.",
        date: '2026-03-04',
        first_name: 'Desk',
        last_name: 'Dweller',
        user_name: 'desk_job_hero',
        is_admin: false,
        post_id: 20,
        post_title: 'Yoga for Posture',
    },
    {
        id: 21,
        comment:
            'The 2-5-1 is the bread and butter of everything! Have you tried adding some 9ths or 13ths to your voicings?',
        date: '2026-01-22',
        first_name: 'Miles',
        last_name: 'Davis',
        user_name: 'miles_jazz',
        is_admin: false,
        post_id: 21,
        post_title: 'Jazz Piano',
    },
    {
        id: 22,
        comment: "Thrifting is so rewarding. It's like a treasure hunt every time you go.",
        date: '2026-02-18',
        first_name: 'Eco',
        last_name: 'Emma',
        user_name: 'emma_thrifter',
        is_admin: false,
        post_id: 22,
        post_title: 'Sustainable Fashion',
    },
    {
        id: 23,
        comment:
            "I strictly play the London System because I'm too lazy to learn the Sicilian theory. It’s a bit boring, but at least I don't lose my queen in the first 10 moves like I do against the Najdorf. Mad respect to anyone who can actually memorize all those lines without their head exploding.",
        date: '2026-01-11',
        first_name: 'Chess',
        last_name: 'Noob',
        user_name: 'pawn_star',
        is_admin: false,
        post_id: 23,
        post_title: 'The Sicilian Defense',
    },
    {
        id: 24,
        comment: 'Which app? Calm or Headspace?',
        date: '2026-03-06',
        first_name: 'Zen',
        last_name: 'Zoe',
        user_name: 'zoe_zen',
        is_admin: false,
        post_id: 24,
        post_title: 'Meditation',
    },
    {
        id: 25,
        comment: 'Fenders are a must for rainy rides. Otherwise, you get that nasty stripe of mud up your back.',
        date: '2026-02-27',
        first_name: 'Biker',
        last_name: 'Bill',
        user_name: 'billy_wheels',
        is_admin: false,
        post_id: 25,
        post_title: 'Cycling in the Rain',
    },
    {
        id: 26,
        comment:
            "I tried the 24-hour rest and you're right, the texture is completely different. It's much chewier and the edges get that nice crispiness. My kids didn't want to wait that long but I hid half the dough in the back of the fridge so they couldn't find it until the next day! Definitely worth the effort.",
        date: '2026-02-09',
        first_name: 'Cookie',
        last_name: 'Monster',
        user_name: 'cookie_mom',
        is_admin: false,
        post_id: 26,
        post_title: 'The Secret to Perfect Chocolate Chip Cookies',
    },
    {
        id: 27,
        comment: 'Once you go ultrawide, you can never go back to dual monitors.',
        date: '2026-03-03',
        first_name: 'Gamer',
        last_name: 'Guy',
        user_name: 'ultrawide_fan',
        is_admin: false,
        post_id: 27,
        post_title: 'Desktop Setup',
    },
    {
        id: 28,
        comment: 'Minimalism is so freeing. I donated 5 bags of clothes today!',
        date: '2026-02-14',
        first_name: 'Simple',
        last_name: 'Sam',
        user_name: 'sam_simple',
        is_admin: false,
        post_id: 28,
        post_title: 'Minimalism',
    },
    {
        id: 29,
        comment:
            "I agree that roles will evolve, but I'm worried about the entry-level market. If AI handles the 'grunt work,' how will juniors ever get the experience they need to become the 'curators' and 'directors' you're talking about? We might be creating a massive talent gap in the next 5 to 10 years if we aren't careful about how we integrate these tools in corporate training.",
        date: '2026-01-05',
        first_name: 'Future',
        last_name: 'Fred',
        user_name: 'fred_tech_talk',
        is_admin: true,
        post_id: 29,
        post_title: 'The Future of AI',
    },
    {
        id: 30,
        comment: 'Guilty of overwatering my succulents... oops.',
        date: '2026-03-11',
        first_name: 'Plant',
        last_name: 'Paul',
        user_name: 'paul_plants',
        is_admin: false,
        post_id: 30,
        post_title: 'Stop Overwatering!',
    },
    {
        id: 31,
        comment: "The first 10k is easy, it's the last 5k where the real mental battle happens. Keep going!",
        date: '2026-02-22',
        first_name: 'Runner',
        last_name: 'Rich',
        user_name: 'rich_runs',
        is_admin: false,
        post_id: 31,
        post_title: 'Half-Marathon Training',
    },
    {
        id: 32,
        comment: 'I always forget the syntax for dict comprehensions though.',
        date: '2026-03-01',
        first_name: 'Python',
        last_name: 'Pete',
        user_name: 'pete_py',
        is_admin: false,
        post_id: 32,
        post_title: 'Python Tips',
    },
    {
        id: 33,
        comment: "Chemex is great but it's so fragile. I've broken two this year already.",
        date: '2026-01-18',
        first_name: 'Clumsy',
        last_name: 'Cate',
        user_name: 'cate_clumsy',
        is_admin: false,
        post_id: 33,
        post_title: 'Coffee Brewing',
    },
    {
        id: 34,
        comment:
            "I started my capsule wardrobe last month. The hardest part was getting rid of the 'just in case' items that I haven't worn in 3 years. But now that they're gone, I feel so much lighter. I only have 25 items now and I actually feel like I have more to wear than before. It’s a weird psychological shift but a very positive one.",
        date: '2026-02-11',
        first_name: 'Minimal',
        last_name: 'Mary',
        user_name: 'mary_less',
        is_admin: false,
        post_id: 34,
        post_title: 'My Journey Toward a Capsule Wardrobe',
    },
    {
        id: 35,
        comment: 'The soundtrack to Chrono Trigger is still the best in gaming history.',
        date: '2026-03-09',
        first_name: 'Retro',
        last_name: 'Rob',
        user_name: 'rob_games',
        is_admin: false,
        post_id: 35,
        post_title: 'Retro Gaming',
    },
    {
        id: 36,
        comment: 'Interfaces and Types saved my project last week when we did a major refactor. TS is king.',
        date: '2026-02-26',
        first_name: 'Code',
        last_name: 'Chris',
        user_name: 'chris_dev',
        is_admin: true,
        post_id: 36,
        post_title: 'TypeScript is Essential',
    },
    {
        id: 37,
        comment: 'Wes Anderson is the king of breaking the rule of thirds with symmetry.',
        date: '2026-01-25',
        first_name: 'Film',
        last_name: 'Fan',
        user_name: 'movie_buff_99',
        is_admin: false,
        post_id: 37,
        post_title: 'Cinematography',
    },
    {
        id: 38,
        comment:
            "I'm planning a trip to Kyoto in October. Any specific temples that aren't too crowded? I really want to experience the quiet side of Japan without being surrounded by thousands of tourists taking selfies. I've heard there are some hidden ones in the northern part of the city but I'm not sure which ones are worth the trek.",
        date: '2026-02-14',
        first_name: 'Travel',
        last_name: 'Tara',
        user_name: 'tara_trips',
        is_admin: false,
        post_id: 38,
        post_title: 'Solo Travel in Japan',
    },
    {
        id: 39,
        comment: 'Walnut is a tough wood to work with but it looks so high-end when finished. Post pics!',
        date: '2026-03-05',
        first_name: 'Woody',
        last_name: 'Wood',
        user_name: 'woody_diy',
        is_admin: false,
        post_id: 39,
        post_title: 'Woodworking Project',
    },
    {
        id: 40,
        comment: "Breathwork is so underrated. It's literally free medicine.",
        date: '2026-03-10',
        first_name: 'Mindful',
        last_name: 'Mike',
        user_name: 'mike_breathe',
        is_admin: false,
        post_id: 40,
        post_title: 'Mindfulness',
    },
];
