const createTablesSQL = `
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    user_name TEXT NOT NULL,
    avatar_url TEXT,
    bio TEXT,
    location TEXT,
    birthday_date TEXT,
    password TEXT NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (user_name)
);

CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    post_title TEXT NOT NULL,
    post_content TEXT NOT NULL,
    created_at TIMESTAMPTZ(0) DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ(0) DEFAULT NOW ()
);

CREATE TABLE IF NOT EXISTS post_user (
    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    CONSTRAINT pk_post_user
        PRIMARY KEY (post_id, user_id),

    CONSTRAINT fk_post_user_post
        FOREIGN KEY (post_id)
        REFERENCES posts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_post_user_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comment_user (
    comment_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    CONSTRAINT pk_comment_user
        PRIMARY KEY (comment_id, user_id),

    CONSTRAINT fk_comment_user_comment
        FOREIGN KEY (comment_id)
        REFERENCES comments(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_comment_user_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS post_comment (
    post_id INTEGER NOT NULL,
    comment_id INTEGER NOT NULL,

    CONSTRAINT pk_post_comment
        PRIMARY KEY (post_id, comment_id),

    CONSTRAINT fk_post_comment_post
        FOREIGN KEY (post_id)
        REFERENCES posts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_post_comment_comment
        FOREIGN KEY (comment_id)
        REFERENCES comments(id)
        ON DELETE CASCADE
);
`;

const insertToTablesSQL = `
INSERT INTO users (first_name, last_name, user_name, avatar_url, bio, location, birthday_date, password, is_admin)
    VALUES
        ('Olivia', 'Bennett', 'liv_bennett', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609020/sample_ava_1_jrd4f3.png', 'Coffee addict ☕ | Amateur photographer | Hiking every weekend | Currently obsessed with film photography and darkroom development. Ask me about my Pentax K1000.', 'Portland, OR', '1995-03-14', '$2a$16$sGoawBQ6JZyb4mBaY3PRouFJlv.bHILq4jxdVk0m5Z2A4XgJyXpx.', true),
        ('Marcus', 'Delgado', 'marcus_d', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609111/sample_ava_2_ggaaqh.jpg', 'just a guy', 'Austin, TX', '1992-07-22', '$2a$16$UhxdB9Ai1HS0XgitvVIYwO0eDhM7uE91O.xt7U/rtjAUsE6GefKP.', false),
        ('Yuki', 'Tanaka', 'yuki_t', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609110/sample_ava_3_fxcxej.jpg', 'Software engineer by day, home chef by night. I document every dish I cook — over 300 recipes and counting. Currently learning to make proper ramen from scratch. It''s a 3-day process and absolutely worth it.', 'San Francisco, CA', '1998-11-05', '$2a$16$IjrZZjAuuYEbbWmbpzU.verjTZXaxM1gdtQ/IuqFVv.B8z0Xktxf6', false),
        ('Derrick', 'Osei', 'd_osei', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609111/sample_ava_4_xvxayq.jpg', 'idk what to write here lol', 'Atlanta, GA', '2000-01-30', '$2a$16$H4tHlr.eyisUErJlhEJAi.aLpp98.XL3hHWSzArLB21tsF8Qa7jzK', false),
        ('Sofia', 'Marchetti', 'sofia_m', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609111/sample_ava_5_aojk6a.jpg', 'Architect and urban planner passionate about sustainable cities. I believe good design is invisible — it just makes life feel right. Milan born, now building a life in New York one small apartment at a time.', 'New York, NY', '1990-06-18', '$2a$16$TV02o8wsMoZ4iOky1uGYW.W/tzV45An2e9BwCInz0sd1CdjYUdWMC', true),
        ('Ethan', 'Cho', 'ethancho_', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609111/sample_ava_6_phlhkt.png', 'music. sleep. repeat.', 'Seattle, WA', '2001-09-09', '$2a$16$BW4PLws8N1MC0rj3ENXsSesc/rwoRgi.rvxA12Uc62pFNVJ2FbyNO', true),
        ('Amara', 'Nwosu', 'amara_nwosu', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609111/sample_ava_7_em1a1w.jpg', 'Nurse, mom of two, part-time marathon runner. I started running at 34 to prove something to myself — ended up qualifying for Boston at 37. Life is long if you keep moving.', 'Houston, TX', '1986-04-02', '$2a$16$BCeENbkfbTU.1Xt1fwpfqeb5LO9VzR2x5FGdIUiUbaqW6XpQV7m7C', false),
        ('Leo', 'Hartmann', 'leo_ha', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609110/sample_ava_8_i37l6n.jpg', 'exist.', 'Chicago, IL', '1997-12-25', '$2a$16$L9uKOfE5IBpoUg2FZkKH..rmFxKPzA.NsMc55wuu51Rb/RNzbbs2W', false),
        ('Priya', 'Sharma', 'priya_sharma', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609110/sample_ava_9_mjanx6.jpg', 'PhD candidate in computational neuroscience. Trying to understand how the brain encodes memory — and also trying to remember where I put my keys every single morning. The irony is not lost on me.', 'Boston, MA', '1994-08-17', '$2a$16$LSOliJEr1kMTt76j8WzYveoBSzK/PwgadbeHkFE3A6YjmwY9jqRvG', false),
        ('Carlos', 'Rivera', 'carlitos_rv', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609110/sample_ava_10_rmrcub.jpg', 'Former chef, current food truck owner. My abuela''s recipes, my twist. Find me on 5th and Main on Fridays.', 'Miami, FL', '1988-02-14', '$2a$16$Dj4byBQsAVnvJDndUC6iOud7.fDvMYqM97pM5rbKvcQMfAEiBK.ia', false),
        ('Zoe', 'Petrov', 'zoe_ptrv', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609110/sample_ava_11_y2rvxj.jpg', '🌱🐈‍⬛✨', 'Denver, CO', '2002-05-11', '$2a$16$QR3zHvoe.i3TU5xWsSgevevtPDD79kYPw0C0Wc3xS0E.IqVunobRO', false),
        ('James', 'Whitfield', 'jwhit_field', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609110/sample_ava_12_yc0w1w.jpg', 'Retired Navy officer. Now I sail recreationally, grow tomatoes, and argue about history online. Proud grandfather of four. Still wake up at 0500 out of habit.', 'Annapolis, MD', '1965-10-03', '$2a$16$NClA9gauL.UjQR.oFxkju.8W5m6IjHmbf5HuN//CLFpqNvVcUlK/K', false),
        ('Nina', 'Kowalski', 'nina_kow', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609111/sample_ava_13_oaggtu.jpg', 'graphic designer. i make things look nice for companies that don''t appreciate it', 'Brooklyn, NY', '1996-03-28', '$2a$16$8JffayycuttujXAyfT6woemoVHKpqByrpROygWn4FyY8s4VA.zTh2', false),
        ('Ravi', 'Menon', 'ravi_menon', 'https://res.cloudinary.com/dv2usnwu2/image/upload/v1774609111/sample_ava_14_wyogv4.jpg', 'Entrepreneur, investor, and lifelong learner. I''ve started 4 companies — 2 failed spectacularly, 1 was acquired, 1 is still alive and kicking. Failure is just tuition. Always happy to chat with founders.', 'San Jose, CA', '1983-07-07', '$2a$16$B742M.RW0jngeMZG4pVJpu9EE0IU4hI2YHIzqOtjf.l8OaqUt5P7O', false)
;

INSERT INTO posts (post_title, post_content, created_at)
    VALUES
        ('First roll with the Pentax K1000', 'Finally finished developing my first roll of Kodak Gold 200 in the darkroom last night. There''s something almost meditative about the whole process — the complete darkness, the smell of the chemicals, watching an image slowly appear in the developer tray. Three of the shots came out genuinely beautiful. The rest were either overexposed or I forgot to advance the film properly. Still. I''m hooked.', '2024-01-08 00:00:00+00'),
        ('my setup rn', 'lo-fi beats, rain outside, green tea. life is ok', '2024-01-09 00:00:00+00'),
        ('Ramen Day 1 — The Broth Begins', 'Started the tonkotsu broth this morning at 6am. Blanched the pork bones first to get rid of the scum, then into a rolling boil for the next 12 hours. My entire apartment smells like a ramen shop and I genuinely don''t hate it. The goal is a broth that''s milky white, rich, and coats the back of a spoon. Will update tomorrow when I start on the tare and the chashu.', '2024-01-10 00:00:00+00'),
        ('thoughts on sustainable housing in NYC', 'Had a long conversation with a colleague today about passive house standards and whether they''re actually achievable at scale in New York. The short answer is yes, but it requires buy-in from developers who are used to cutting corners on insulation and mechanical systems. The longer answer involves zoning reform, updated energy codes, and a city government willing to incentivize rather than just mandate. I''ve been working on a proposal for a mixed-use building in the Bronx that uses cross-laminated timber and a centralized heat recovery ventilation system. The embodied carbon numbers are promising. More on this soon.', '2024-01-11 00:00:00+00'),
        ('Boston qualifier', 'I qualified for Boston. I''m still shaking. 3:41:22 at the Houston Marathon this morning. The standard for my age group is 3:50. I ran it in a tank top in January because it was 68 degrees and humid and none of that mattered. Miles 18 through 22 were the hardest miles of my life. I talked to my late mother in my head for the last four miles. I think she helped.', '2024-01-12 00:00:00+00'),
        ('free will is not a thing and here''s why', 'I''ve been down a rabbit hole of determinism papers this week and I genuinely can''t find a coherent argument for libertarian free will that doesn''t eventually rely on something unprovable. Every decision we make is the result of prior brain states, which are the result of prior experiences, which we didn''t choose. Even the feeling of choosing feels more like a post-hoc narrative we construct than an actual causal force. I''m not saying this is depressing. I actually find it kind of freeing? If I''m not truly ''responsible'' for my worst moments then I''m also not taking credit for my best ones either. Anyway. It''s late.', '2024-01-13 00:00:00+00'),
        ('food truck is official', 'Permit approved. Truck wrapped. Menu finalized. We open Friday on 5th and Main. My abuela''s arroz con pollo, her picadillo, and a short rib taco that''s all mine. Come find us.', '2024-01-14 00:00:00+00'),
        ('my plants are thriving and so am i (kinda)', 'the monstera put out two new leaves this week. take notes everyone', '2024-01-15 00:00:00+00'),
        ('What they don''t tell you about founding a company', 'Nobody warns you that the hardest part of building a company isn''t the product, the fundraising, or even the hiring. It''s the psychological weight of carrying other people''s livelihoods. When my second company started running out of runway in 2018, I remember lying awake not worried about my own salary but about the 11 people who had believed in me enough to leave stable jobs. We ended up shutting down anyway. I paid everyone their last two months out of my own pocket. I''d do it again. But I wish someone had sat me down before company number one and said: ''This is going to change how you think about responsibility forever.''', '2024-01-16 00:00:00+00'),
        ('darkroom mistake turned into my favorite print', 'Accidentally double-exposed a sheet of fiber paper last night and the result is genuinely one of the most interesting things I''ve ever printed. A portrait of my friend layered over a shot of bare tree branches. It looks intentional. Sometimes the mistake is the work.', '2024-01-17 00:00:00+00'),
        ('can''t sleep', '3am and my brain won''t stop. not even sad just. awake.', '2024-01-18 00:00:00+00'),
        ('Ramen Day 3 — Final Result', 'It''s done. 72 hours of work across three days and I''m sitting here with a bowl of tonkotsu ramen that genuinely rivals some of the best I''ve had in Japan. The broth is silky and rich. The chashu melts. The ajitsuke tamago — soft-boiled eggs marinated overnight in soy, mirin, and sake — have the most beautiful jammy yolk. I made a batch of noodles from scratch too, using bread flour and kansui water for that slight chew. My roommate tasted it and said nothing for about 30 seconds and then said ''you can''t ever stop making this.'' I''ll write up the full recipe eventually but honestly I''m not sure I can reduce it to a blog post. It''s more of an experience.', '2024-01-19 00:00:00+00'),
        ('CLT and the future of tall buildings', 'Cross-laminated timber is having a moment and it deserves it. Mass timber buildings can sequester carbon rather than emit it during construction, they''re faster to build than concrete, and — this surprised even me when I first learned it — they perform remarkably well in fire conditions because large timber sections char on the outside and maintain structural integrity far longer than unprotected steel. The tallest mass timber building in the world right now is 85.4 meters in Milwaukee. I think we''ll see that record broken multiple times in the next decade.', '2024-01-20 00:00:00+00'),
        ('training log — week 1 post-race', 'Doctor said take two weeks completely off after Houston. I lasted four days. Did an easy 4 miles this morning, nothing hurt, legs felt fresh. I know I should rest but my brain doesn''t know what to do with itself when I''m not running. Already thinking about what''s next. Maybe a spring half. Maybe just base-building for Boston.', '2024-01-21 00:00:00+00'),
        ('the memory encoding thing', 'Presented some early data at lab meeting today on how the hippocampus differentiates between similar spatial contexts during encoding. Nothing groundbreaking yet but there''s a pattern in the theta oscillation data that I can''t stop thinking about. Science moves so slowly and then sometimes you''re staring at a graph at 11pm and something clicks and you forget to eat dinner.', '2024-01-22 00:00:00+00'),
        ('Friday was insane', 'Sold out in two hours. TWO HOURS. We had people lining up before we even opened the window. I had to call my cousin to come help and she''d never worked a food truck in her life. She burned herself on the plancha twice and kept going. That''s family.', '2024-01-23 00:00:00+00'),
        ('anyone else feel like they''re performing productivity', 'like i sit at my desk, have the right tabs open, look busy, and produce maybe 40 minutes of actual work in 8 hours. and somehow that''s just. normal??', '2024-01-24 00:00:00+00'),
        ('Sailing trip — Chesapeake Bay, January', 'Took the Catalina out last weekend despite the cold. My crew was just my neighbor Bill and my grandson Tyler, who is 9 and has decided he wants to be a sailor. We motored out of the slip in 38-degree air, raised the main once we cleared the marina, and had a perfectly quiet two hours on the water. Tyler asked me if I was scared at sea when I was in the Navy. I told him the honest answer: sometimes, but the training made the fear manageable. He thought about that for a while and then asked if we could have hot chocolate. We could.', '2024-01-25 00:00:00+00'),
        ('rebranding a client who doesn''t know what they want', 'week 3 of ''we''ll know it when we see it.'' currently on logo revision 14. FOURTEEN.', '2024-01-26 00:00:00+00'),
        ('why I tell every founder to embrace the failure', 'I gave a talk at a startup event in San Jose last night and as usual someone asked me about my two failed companies. I used to feel a twinge of embarrassment answering that question. Now I lean into it completely. My first failure taught me about co-founder alignment — we had great chemistry socially but fundamentally different risk tolerances. My second taught me about timing. The market wasn''t ready. The product was good, actually. We were just early by about three years, and a well-funded competitor launched the same concept in 2021 and raised a Series B. That stings a little differently than outright failing. But both experiences are why the company I''m running now is the best-managed thing I''ve ever built. Every scar is a lesson you can''t learn from a book.', '2024-01-27 00:00:00+00'),
        ('shot on expired film', 'Used a roll of expired Fuji Superia 400 from 2009 that I found in a thrift store camera. The color shift is wild — everything has a green-magenta cast that makes the photos look like they''re from a fever dream. Shot a whole roll around the neighborhood at dusk. Can''t decide if this is art or a happy accident. Probably both.', '2024-01-28 00:00:00+00'),
        ('update on the thesis', 'My advisor told me today that I''m ''making progress'' which from her means I''m doing fine. She has three modes: silence, ''making progress,'' and ''this is publishable.'' I''ve never heard the third one directed at me. I''ll take it.', '2024-01-29 00:00:00+00'),
        ('denver in winter is underrated', '300 days of sun a year and people still act surprised. I went hiking yesterday in a t-shirt. it was January 30th.', '2024-01-30 00:00:00+00'),
        ('abuela''s picadillo recipe — the real one', 'A lot of people have been asking since the truck opened so here it is, as best as I can write it down. The thing about abuela''s cooking is she never measured anything, so these are approximations. Brown a pound and a half of ground beef with diced onion and green pepper. Don''t drain the fat — that''s flavor. Add a full head of minced garlic. A cup of tomato sauce. A big handful of green olives with pimentos, roughly chopped. Two teaspoons of cumin. Salt, pepper, a little oregano. Some people add raisins here. Abuela did not. Once it''s all combined, taste it. Adjust. Taste again. Serve over white rice that you''ve cooked with a bay leaf and a little butter. Simple. Perfect.', '2024-01-31 00:00:00+00'),
        ('I rewired my bathroom light and did not die', 'YouTube university continues to educate me. The flickering is gone. I''m very proud of myself.', '2024-02-01 00:00:00+00'),
        ('on designing for people you''ll never meet', 'The most humbling part of urban design is that the spaces I create will be used by hundreds of thousands of people who have no idea I exist. A well-placed bench, a covered walkway, a plaza with enough shade — these become part of someone''s daily life without them ever thinking about who chose to put them there. That''s the whole point. Good design disappears. It just becomes the world.', '2024-02-02 00:00:00+00'),
        ('my brain at 2am: is glass a liquid', 'it''s not. i looked it up. anyway.', '2024-02-03 00:00:00+00'),
        ('10 miles in the snow', 'Ran 10 miles this morning in actual snowfall. Houston never gets snow so I have no idea what I''m doing but my legs felt strong and I ran the last two miles faster than the first. Coach would call that negative splits. I just call it not wanting to be cold anymore.', '2024-02-04 00:00:00+00'),
        ('The Peloponnesian War and why it still matters', 'Finished Thucydides again last week — the Crawley translation this time after years of reading Strassler. There''s a reason this book has been studied continuously for 2,400 years. The Melian Dialogue alone should be required reading for every diplomat and policymaker alive. ''The strong do what they can and the weak suffer what they must.'' We haven''t changed. The technology changes. The logic of power doesn''t. I''ve argued about this passage with people online for two decades and I''m still not tired of it.', '2024-02-05 00:00:00+00'),
        ('client feedback be like', '''can you make the logo bigger, more modern, but also more classic, and maybe add something that really pops but also is subtle.'' sure. absolutely. on it.', '2024-02-06 00:00:00+00'),
        ('Fujifilm vs Kodak — a completely subjective take', 'I''ve been shooting both for about eight months now and here''s where I''ve landed. Kodak Gold 200 for warm light, golden hour, portraits of people I love — it has this slightly soft, honeyed quality that feels nostalgic in a way that doesn''t feel manufactured. Fuji 400H for overcast days, architecture, anything where I want cooler tones and a bit more clinical sharpness. Neither is objectively better. They''re different moods. Anyone who tells you one is superior is probably just justifying what they already bought.', '2024-02-07 00:00:00+00'),
        ('the thing about startups nobody says out loud', 'Most startup advice is written by people who succeeded and then retrofitted a narrative onto the chaos. Survivorship bias is everywhere in this industry. For every ''I did these five things and we hit product-market fit'' post there are a thousand companies that did the same five things and shut down. I don''t have a solution to this. I just think founders should read the failure post-mortems at least as often as the success stories.', '2024-02-08 00:00:00+00'),
        ('spilled matcha on my sketchbook', 'not a metaphor. just a bad morning. the drawing underneath is kind of interesting now though', '2024-02-09 00:00:00+00'),
        ('hippocampal replay during sleep', 'There''s a fascinating body of research on how the hippocampus ''replays'' the day''s experiences during sleep — essentially consolidating episodic memories into long-term storage. What I keep coming back to is whether this replay is purely a compression mechanism or whether it also involves some kind of evaluation, a filtering of what matters. Some models suggest the emotional tag attached to a memory influences how strongly it gets replayed. Which could explain why we remember embarrassing moments from middle school with perfect clarity but forget entire months of routine.', '2024-02-10 00:00:00+00'),
        ('new record on the truck', 'Served 140 people in one lunch shift today. My arm feels like it''s going to fall off but the register doesn''t lie. Saturday is going to be even bigger. I need to hire someone.', '2024-02-11 00:00:00+00'),
        ('february playlist is up', 'lots of this: slow jazz, one or two ambient tracks, a few old soul songs my dad used to play. link in bio if you want it', '2024-02-12 00:00:00+00'),
        ('Half marathon — 1:44', 'Ran the Galveston Half Marathon this morning. 1:44:07. Not a PR but a solid training run. The course is flat and fast and the sea breeze at mile 8 genuinely saved me. The real goal is Boston in April and today was a confidence check. I feel ready. I think I feel ready.', '2024-02-13 00:00:00+00'),
        ('A letter to younger me, sort of', 'I was going through old boxes in the attic last week and found my journal from my first deployment in 1987. Reading it was strange — like meeting someone who shares all your memories but has a completely different relationship with fear and uncertainty. Twenty-three-year-old James was certain about everything in the loud, brittle way that young people are. I wanted to tell him to listen more. To sit with doubt instead of fighting it. But I also know he wouldn''t have listened. That''s the thing about experience — you can''t transfer it. You can only accumulate it.', '2024-02-14 00:00:00+00'),
        ('do brands deserve emotions', 'had a brand meeting where the client said their brand should feel ''curious but also reliable, playful but professional, approachable but premium.'' i smiled and said yes and then went home and stared at my ceiling', '2024-02-15 00:00:00+00'),
        ('Sourdough attempt #4', 'The starter is alive and well — I''ve named her Priya Jr. which my labmates think is hilarious. The loaf itself came out with a decent ear and an open crumb but the crust went soft overnight. I think I didn''t steam the oven enough in the first 15 minutes. Attempt 5 will involve a Dutch oven instead of the steam injection method.', '2024-02-16 00:00:00+00'),
        ('found a camera at a garage sale', 'Olympus XA2 in perfect condition for $4. The lady selling it said it was her husband''s and he never used it. Loaded it with a roll of Lomo 800 and I''m going to shoot the whole thing this weekend. This little camera fits in my jacket pocket. I love it.', '2024-02-17 00:00:00+00'),
        ('what makes a city walkable — actually', 'Walkability scores are well-intentioned but they miss a lot. A high Walk Score doesn''t tell you whether the sidewalks feel safe at night, whether there''s adequate shade in a hot climate, whether the street-level experience is interesting enough to make people want to walk rather than drive. The human-scale details matter enormously: trees, benches, varied storefronts, windows that look onto the street, wide sidewalks with a clear buffer from traffic. I walked from my apartment in Brooklyn to my office last week — about 2.4 miles — and noticed for the first time how dramatically the quality of the walking experience changes block by block. We have the tools to design better urban environments. We mostly choose not to use them.', '2024-02-18 00:00:00+00'),
        ('hired my first employee', 'Her name is Valentina. She''s 20, she''s fast, she doesn''t complain, and she learned the whole menu in two days. I gave her a raise on day three. Good people are rare.', '2024-02-19 00:00:00+00'),
        ('reading on a tuesday', 'currently: a novel about a lighthouse keeper. it''s very slow and very good. that''s all', '2024-02-20 00:00:00+00'),
        ('VC culture is broken and I''ll die on this hill', 'The incentive structure of venture capital is fundamentally misaligned with building healthy, sustainable companies. VCs need outlier returns to justify their fund economics, which means they push portfolio companies toward hypergrowth strategies that often destroy culture, burn out teams, and prioritize growth metrics over actual value creation. I''ve taken VC money twice. I understand why it exists. I also think it''s caused more damage to the startup ecosystem than anyone wants to admit publicly. My current company is profitable and growing at a pace my team can actually sustain. We''ve had term sheets. We''ve turned them down. I sleep well.', '2024-02-21 00:00:00+00'),
        ('8 miles before sunrise', 'Out the door by 5:15am. It was still dark for the first two miles and the city was quiet in a way it almost never is. Passed a guy walking his dog who nodded at me like we were in a secret club. We are, kind of.', '2024-02-22 00:00:00+00'),
        ('the theta rhythm thing keeps bothering me', 'okay i know i keep coming back to this but the 4-8hz theta oscillations in CA1 during active navigation are showing up in our data in a context that doesn''t fit the standard spatial coding model. i''ve read every paper I can find. i''m either missing something obvious or there''s something interesting here. meeting with my advisor friday. trying not to get too excited.', '2024-02-23 00:00:00+00'),
        ('grandkids for the weekend', 'All four of them, ages 4 through 12. My wife and I are exhausted in the best possible way. We baked cookies. We watched a movie about talking animals. Tyler taught his cousins the names of the sails on a sailboat. I don''t think they retained any of it. It was a perfect weekend.', '2024-02-24 00:00:00+00'),
        ('logo revision 21', 'they liked it. THEY LIKED IT. I''m going to sit outside and breathe real air for ten minutes', '2024-02-25 00:00:00+00'),
        ('Sourdough #5 — success', 'Dutch oven method works. The crust shattered when I tapped it. The crumb was open and chewy. It tasted like actual bread. I may have cried a little. My roommate ate three slices with just butter and said nothing else needed to be said.', '2024-02-26 00:00:00+00'),
        ('shooting portraits of strangers', 'I''ve been working up the nerve to do street portraiture and yesterday I finally asked someone — a woman selling flowers outside a shop on Division Street. I explained what I was doing, showed her the camera, asked if she''d mind. She said yes, posed without being asked, and then asked to see the viewfinder which of course is a film camera so there''s nothing to see. We laughed about it. I''ll get the prints back in a week. Regardless of how they look the conversation was worth it.', '2024-02-27 00:00:00+00'),
        ('the texture of cities', 'New York has a texture. You feel it through your shoes. The subway grates, the uneven sidewalk slabs, the metal cellar doors embedded in the pavement. Every city has its own material vocabulary and New York''s is patched, improvised, layered. The old under the new under the newer. I love it. Milan is the opposite — precise, deliberate, maintained. Both are beautiful for completely different reasons.', '2024-02-28 00:00:00+00'),
        ('rest day', 'Full rest. No running. Ate pasta and watched TV. This is also training.', '2024-03-01 00:00:00+00'),
        ('on knowing when to shut a company down', 'This is something I think about a lot and don''t hear discussed honestly enough. There''s a culture in startups of perseverance that can curdle into denial. ''Keep going'' is good advice until it isn''t. The founders I''ve seen hurt the most were the ones who burned through their savings, their relationships, and two extra years of their lives on a company that the evidence was telling them to close eighteen months earlier. Part of my job now — informally, with founders I mentor — is to help people distinguish between a hard patch that requires pushing through and a fundamental problem that no amount of pushing will fix. It''s not a clean distinction. But learning to see it is maybe the most important skill in this industry.', '2024-03-02 00:00:00+00'),
        ('got my film scans back', 'The flower seller portrait is everything I hoped for. Sharp eyes, slightly soft background from the 50mm at f/2, and that Lomo 800 grain that makes everything look like a memory you''re trying to hold onto. I''m printing this one large.', '2024-03-03 00:00:00+00'),
        ('new menu item testing', 'Working on a slow-cooked oxtail dish to add for weekends only. Braised for five hours with sofrito, red wine, tomato, and spices. The meat falls off the bone. Over yellow rice with sweet plantains on the side. Not traditional, not fusion — just food that makes sense together. First public test is Saturday. Nervous in a good way.', '2024-03-04 00:00:00+00'),
        ('typography nerd post incoming', 'can we talk about how grotesque sans-serifs became the default for every tech brand circa 2015 and nobody''s questioned it since? like yes Helvetica is clean and yes Inter is readable and yes I know why you chose them. but there''s a whole universe of type design out there and we keep eating the same meal. a well-chosen serif can communicate so much more personality. anyway. I just rebranded a bakery using a custom lettering wordmark and it looks incredible and I''m very normal about it', '2024-03-05 00:00:00+00'),
        ('advisor meeting went well', 'She thinks the theta data is worth pursuing. We''re going to run a targeted follow-up experiment in the next cohort. This means at least six more months on this specific question but I think it''s the right call. Trying to publish something inconclusive would be worse than waiting.', '2024-03-06 00:00:00+00'),
        ('tomatoes are coming in', 'Eight plants this year, four varieties. The Brandywines are huge and ugly and taste like summer used to. The Sun Golds are already producing and I eat them warm off the vine standing in the garden in the morning. My neighbors keep asking what I do differently. I tell them I talk to the plants. This is true.', '2024-03-07 00:00:00+00'),
        ('20-miler done', 'Last long run before Boston. 20.2 miles in 3:01. Fueled with gels at miles 5, 10, 14, and 18 — nothing fell apart, no wall. Legs are tired but not broken. Two weeks of taper now. I''m ready to be done with training and ready to race.', '2024-03-08 00:00:00+00'),
        ('procrastinating by reorganizing my desk', 'it looks so clean now. still haven''t done the thing I was supposed to do. worth it', '2024-03-09 00:00:00+00'),
        ('passive house — the retrofit problem', 'Everyone talks about passive house in the context of new construction, but the real challenge — and opportunity — is retrofitting existing buildings. In New York, most of the housing stock that will exist in 2050 is already built. We can''t just tear it down and start over. Deep energy retrofits are expensive and disruptive. They require residents to move out temporarily. They''re often blocked by condo boards or constrained by landmarking restrictions. And yet this is where 80% of the work needs to happen. The green building conversation needs to shift from showcase new builds to the boring, difficult, unglamorous work of improving what already exists.', '2024-03-10 00:00:00+00'),
        ('made miso from scratch', 'Started a batch of shiro miso. Cooked soybeans, mixed with rice koji and salt, packed into a crock with a weight on top, and now it just… waits. Minimum three months. I labeled the crock with today''s date and put it in the back of the pantry. Fermentation is the most patient kind of cooking.', '2024-03-11 00:00:00+00'),
        ('book recommendation', 'just finished ''the overstory'' by richard powers. i''m not ok. please read it.', '2024-03-12 00:00:00+00'),
        ('street photography rules I made up for myself', '1. Never shoot someone from behind if you can help it. 2. If someone sees you and looks uncomfortable, lower the camera. 3. If someone asks you to delete it, delete it — no argument. 4. The best time is the hour after sunrise and the hour before sunset. 5. Walk the same street multiple times. You see different things each time. 6. The photo you almost didn''t take is usually the best one.', '2024-03-13 00:00:00+00'),
        ('the oxtail sold out in 40 minutes', 'Made 30 portions. Gone by 12:40pm. Next week I''m making 50. This is the best problem I''ve ever had.', '2024-03-14 00:00:00+00'),
        ('imposter syndrome is a liar but also constant', 'I have a PhD advisor who believes in my work, a paper under review at a solid journal, and data that might be genuinely interesting. I also woke up this morning convinced that I am a fraud who has fooled everyone for six years and will be exposed soon. Both things are true at the same time. I asked a senior postdoc about this and she laughed and said ''oh that never goes away.'' Wonderful.', '2024-03-15 00:00:00+00'),
        ('the problem with ''move fast and break things''', 'The phrase was coined in the context of a social network for college students. It became a philosophy applied to healthcare, finance, transportation, housing, and critical infrastructure. Moving fast and breaking things is fine when ''things'' are UI components. It''s less fine when ''things'' are people''s medical records, retirement savings, or the communities displaced by the tech campuses you built. I don''t think Mark Zuckerberg intended for it to become a moral framework. But it did. And we''re still cleaning up after it.', '2024-03-16 00:00:00+00'),
        ('early spring on the Chesapeake', 'The ospreys are back. Every year I look for them as a sign that winter is actually over, and every year they show up exactly when I need them to. Took the boat out alone yesterday morning and saw three of them circling over the shallows. The water is still cold enough that you''d be in serious trouble if you went in. But the light is changing. You can feel the year turning.', '2024-03-17 00:00:00+00'),
        ('i miss live music', 'went to a show last night and stood in the back and just felt the bass move through me. live music does something to the nervous system that nothing else does. i forget and then i remember.', '2024-03-18 00:00:00+00'),
        ('Boston is in 10 days', 'Taper madness is real. My legs feel fine which means my brain has decided that something must be wrong with them. I''ve eaten more pasta this week than any human should. I''ve checked the weather forecast for Hopkinton seven times. High of 55 and partly cloudy. Perfect racing weather. I just need to not do anything stupid between now and Monday.', '2024-03-19 00:00:00+00'),
        ('on living in small spaces', 'My Brooklyn apartment is 540 square feet. I have exactly what I need and nothing extra. When I visit friends in suburbs with 3,000-square-foot houses I always feel slightly overwhelmed by the sheer volume of space that needs to be managed, heated, furnished, and cleaned. There''s a real freedom in constraint. I know where everything is. I can clean the whole place in 45 minutes. My design instinct for small-space solutions has gotten sharper because I live inside the problem.', '2024-03-20 00:00:00+00'),
        ('the film I shot in Japan, finally', 'I went to Tokyo and Kyoto in November and I''m only now getting the scans back because I shot 22 rolls and the lab was backed up. Going through them is like revisiting a trip I almost forgot. I find things I didn''t consciously notice when I was there — a shadow, a reflection, the way light hit a torii gate at 7am. The camera sees while the eye is busy looking.', '2024-03-21 00:00:00+00'),
        ('a note on building company culture remotely', 'We''ve been fully remote since we started. I know a lot of companies who went remote during 2020 and then rushed back to offices as soon as they could, citing culture. I understand the impulse but I think it misdiagnoses the problem. Weak culture in a remote environment is usually weak culture, period. The office was masking it with proximity and in-person rituals that create the feeling of culture without the substance. The companies I''ve seen maintain strong remote culture are ones where values are explicit, communication norms are written down, and managers are trained to build relationships intentionally rather than passively.', '2024-03-22 00:00:00+00'),
        ('presentation at the lab symposium', 'Presented the theta oscillation work to about 60 people today. Thirty seconds in I forgot that I was nervous. By the end I was genuinely enjoying the questions, even the aggressive one from the professor in the third row who kept saying ''but have you ruled out X.'' Yes. I have ruled out X. It''s in the supplementary materials. Sir.', '2024-03-23 00:00:00+00'),
        ('Boston Marathon — 3:38:54', 'I don''t have enough words. I ran from Hopkinton to Boston. I ran up Heartbreak Hill at mile 21 and I didn''t slow down. I ran down Boylston Street and the sound of the crowd hit me like a wall and I started crying at mile 25.9 and finished crying at the finish line and kept crying for a while after. 3:38:54. A personal best by two minutes and 28 seconds. My mom was with me for the whole 26.2 miles. I know she was.', '2024-04-15 00:00:00+00'),
        ('miso check-in', 'Opened the crock for the first time since March to check on the miso. It smells incredible — salty, deeply savory, a little funky. The color is deepening from white toward pale yellow. Replaced the plastic wrap and the weight and closed it back up. Three more months minimum. Patience.', '2024-06-11 00:00:00+00'),
        ('why I finally deleted Twitter', 'I held on for longer than I should have because I told myself it was useful for following researchers and staying current in my field. That was true for a while. It stopped being true somewhere around 2022 and I spent the next two years being slowly poisoned by a feed that made me angrier and more anxious without making me more informed. I feel genuinely better. I did not expect to feel genuinely better this quickly.', '2024-03-24 00:00:00+00'),
        ('the short rib taco gets a permanent spot', 'After three months of testing I''m officially adding the short rib taco to the permanent menu. Braised short rib, pickled red onion, avocado crema, cotija, cilantro on a fresh corn tortilla. It''s the most me thing on the truck. Abuela would have loved it and probably also suggested adding more garlic. She was always right.', '2024-03-25 00:00:00+00'),
        ('just a photo walk', 'no goal today. no film to finish. just walked around with the Pentax for three hours and shot whatever felt right. some days the process is the whole thing.', '2024-03-26 00:00:00+00'),
        ('the loneliness of long-distance running', 'There''s a quote from Haruki Murakami I keep coming back to: pain is inevitable, suffering is optional. I think about it at mile 18 of every long run, when the body starts sending signals and you have to decide what to do with them. Running a marathon is the loneliest thing I do regularly. Nobody can carry you. Nobody can run your miles for you. But crossing that line with 30,000 other people doing the same lonely thing at the same time is somehow the opposite of lonely.', '2024-03-27 00:00:00+00'),
        ('does anyone else not know how to respond to ''how are you''', 'like actually i''m fine but also there''s so much happening and the honest answer would take 20 minutes and neither of us has time for that so i just say ''good, you?'' and we both move on and that''s probably fine right', '2024-03-28 00:00:00+00'),
        ('Bronx project update', 'The mixed-use timber building I''ve been working on got preliminary approval from the community board last night. 48 units, 30% affordable, mass timber frame, green roof, shared courtyard. It took 14 months to get to this point. We''ve had three complete redesigns in response to community feedback, all of which made the project better. Participatory design is slower. It is also more right.', '2024-03-29 00:00:00+00'),
        ('paper accepted', 'The theta oscillation paper was accepted at the Journal of Neuroscience. Minor revisions. I have been staring at the email for the last 20 minutes. My advisor said ''I told you so'' which is the most emotionally expressive she''s been in six years. I called my parents. My mom cried. I''m going to go eat something and then probably also cry.', '2024-04-01 00:00:00+00'),
        ('the cat showed up', 'there was a cat sitting on my fire escape this morning. i gave it some milk (yes i know). it came back tonight. i don''t have a cat. i might have a cat.', '2024-04-02 00:00:00+00'),
        ('hiring post — if you know anyone', 'We''re looking for a senior product designer to join a 12-person remote team building B2B workflow software. No ping pong tables. No mandatory fun. Competitive salary, actual work-life balance, and a product team that argues thoughtfully and then moves forward. DM me if you know someone who might be a fit.', '2024-04-03 00:00:00+00'),
        ('I grew up on the water and I''ll probably die on it', 'My father had a boat. His father had a boat. I had my first watch on a Navy vessel at 22. Now I have a 32-foot sloop that I sail mostly alone except when Tyler is around. The water teaches patience in a way that nothing ashore does. You cannot argue with weather. You cannot rush a tide. You can only read what''s in front of you and make the best decision available. I think that''s why former sailors make decent leaders. They''ve had the arrogance trained out of them.', '2024-04-04 00:00:00+00'),
        ('my type specimen wall', 'spent all of last saturday printing type specimens and pinning them to the wall above my desk. 40+ fonts, different weights, different sizes, just to live with them and see what I notice. designers will understand. my roommate called it ''the most chaotic art installation she''s ever seen.'' I take that as a compliment.', '2024-04-05 00:00:00+00'),
        ('the miso is done', 'Nine months. I opened the crock this morning and the smell was deep, earthy, complex, and unmistakably miso. Made a simple soup — dashi, cubed tofu, wakame, green onion. Tasted it and laughed out loud alone in my kitchen. Nine months of waiting and it took 10 minutes to use. That ratio seems exactly right.', '2024-12-11 00:00:00+00'),
        ('reflecting on a weird year', 'ran a marathon PR, published my first first-author paper, the truck cleared $200k in revenue for the first time, my cat is named Coriander now, i revised logo number 21 four more times after they said they liked it, and i still don''t know where i left my keys. fine year overall.', '2024-12-31 00:00:00+00'),
        ('a note on grief', 'My wife passed two years ago this week. I don''t write about this much because I''m not sure what to say about it that isn''t already obvious. She was my person for 41 years. The house is still arranged the way she liked it. I''ve only moved one chair. I figure if I ever want to move the chair I will.', '2024-04-06 00:00:00+00'),
        ('marathon training starts again', 'Twelve weeks out from Chicago. First run of the new training block: 6 easy miles, heart rate in zone 2 the whole way. My body remembers. After Boston I told myself I was taking the summer completely off. I took six weeks. That''s close enough.', '2024-07-01 00:00:00+00'),
        ('conference in Copenhagen', 'At a computational neuroscience conference for the week. Copenhagen in July is extraordinary — light until 10pm, everyone on bikes, the most effortlessly livable city I''ve ever visited. Also presented a poster this morning and a researcher from UCL asked for my email to follow up on a potential collaboration. Trying to stay calm about that.', '2024-07-08 00:00:00+00'),
        ('new camera: Hasselblad 500C/M', 'I found a fully serviced Hasselblad 500C/M at a camera fair for $800 — half what they usually go for — because the seller was retiring from photography and wanted it to go to someone who would use it. I shot one test roll and every single frame is tack sharp across the full 6x6 negative. Medium format is a completely different way of seeing. The image quality is almost unfair. I feel like I owe the camera something in return.', '2024-07-15 00:00:00+00'),
        ('catering a wedding — what i learned', 'Said yes to catering a small wedding (40 guests) in March and it was the most logistically complex thing I''ve ever done in food. Triple my usual quantities of everything. Rental equipment I''d never used. A timeline with no margin for error. The picadillo ran out 20 minutes early because I underestimated how much people eat at weddings when the food is good. The couple said it was the best wedding food they''d ever had. I''m still not sure I''d do it again. Actually, I know I would.', '2024-04-20 00:00:00+00'),
        ('things I believe about design that I can''t fully prove', '1. Constraints produce better work than complete creative freedom, almost every time. 2. If you need to explain why a design works, it probably doesn''t. 3. The client is always telling you something useful even when they''re saying it badly. 4. Taste is learnable but takes longer than any school tells you. 5. The best design work I''ve done has always felt slightly inevitable in retrospect.', '2024-04-21 00:00:00+00'),
        ('Chicago Marathon — 3:34:11', 'New personal best. By four minutes and 43 seconds. I ran the second half faster than the first. I did not cry at the finish line this time — I just pumped my fists and screamed something incoherent and kept walking because if I stopped I was going to fall over. My left IT band has something to say about miles 22 onward. But 3:34. I keep typing it to make it real.', '2024-10-13 00:00:00+00'),
        ('Coriander at 6 months', 'she has learned to open the kitchen cabinet where the treats are. she cannot open it but she rattles it with a dedication i can only respect. she sits on my sketchbook when i''m trying to work. she knocked my favorite mug off the table and looked me directly in the eye while she did it. i have never loved anything this much.', '2024-10-14 00:00:00+00'),
        ('the UCL collaboration is happening', 'Signed the agreement for a joint project with the UCL group I met in Copenhagen. We''ll be running parallel experiments in London and Boston looking at hippocampal-prefrontal interactions during memory consolidation. This is the kind of work you spend a PhD dreaming about getting to do. I start the London leg in January.', '2024-11-01 00:00:00+00'),
        ('cold morning, good coffee, no plans', 'this is enough. this is actually enough.', '2024-11-02 00:00:00+00'),
        ('the truck has a second location', 'Signed the agreement for a second truck spot — Thursdays at the Midtown arts district, in addition to our Friday on 5th and Main. Valentina is going to run Thursdays. This is a bigger step than it sounds. I''m trying to grow without losing what makes the truck feel like mine. That tension is something I think about a lot.', '2024-11-15 00:00:00+00'),
        ('i finished a sketchbook for the first time in my life', 'Every other sketchbook I''ve owned: filled maybe 40% of the way and then abandoned on a shelf. This one: every page. Front to back. It took 14 months and the progression from the first page to the last is genuinely embarrassing in the best way.', '2024-11-20 00:00:00+00'),
        ('annual Chesapeake haul-out', 'Pulled the boat out of the water for winter today. Pressure-washed the hull, checked the standing rigging, replaced a shroud that was showing wear. Tyler helped. He''s 10 now and knows the name of every piece of hardware on the boat. I let him do the bottom paint on one whole section by himself. He''s going to be a better sailor than me.', '2024-11-21 00:00:00+00'),
        ('new year, same me, that''s fine', 'I don''t do resolutions. I do intentions. The intention this year: be more patient with myself and less patient with situations I have the power to change. We''ll see how that goes.', '2025-01-01 00:00:00+00')
;

INSERT INTO post_user (post_id, user_id)
    VALUES
        (1, 1),
        (2, 6),
        (3, 3),
        (4, 5),
        (5, 7),
        (6, 9),
        (7, 10),
        (8, 11),
        (9, 14),
        (10, 1),
        (11, 2),
        (12, 3),
        (13, 5),
        (14, 7),
        (15, 9),
        (16, 10),
        (17, 2),
        (18, 12),
        (19, 13),
        (20, 14),
        (21, 1),
        (22, 9),
        (23, 11),
        (24, 10),
        (25, 4),
        (26, 5),
        (27, 2),
        (28, 7),
        (29, 12),
        (30, 13),
        (31, 1),
        (32, 14),
        (33, 11),
        (34, 9),
        (35, 10),
        (36, 6),
        (37, 7),
        (38, 12),
        (39, 13),
        (40, 9),
        (41, 1),
        (42, 5),
        (43, 10),
        (44, 6),
        (45, 14),
        (46, 7),
        (47, 9),
        (48, 12),
        (49, 13),
        (50, 9),
        (51, 1),
        (52, 5),
        (53, 7),
        (54, 14),
        (55, 1),
        (56, 10),
        (57, 13),
        (58, 9),
        (59, 12),
        (60, 7),
        (61, 4),
        (62, 5),
        (63, 3),
        (64, 8),
        (65, 1),
        (66, 10),
        (67, 9),
        (68, 14),
        (69, 12),
        (70, 6),
        (71, 7),
        (72, 5),
        (73, 1),
        (74, 14),
        (75, 9),
        (76, 7),
        (77, 3),
        (78, 9),
        (79, 10),
        (80, 1),
        (81, 7),
        (82, 4),
        (83, 5),
        (84, 9),
        (85, 11),
        (86, 14),
        (87, 12),
        (88, 13),
        (89, 3),
        (90, 8),
        (91, 12),
        (92, 7),
        (93, 9),
        (94, 1),
        (95, 10),
        (96, 13),
        (97, 7),
        (98, 11),
        (99, 9),
        (100, 6),
        (101, 10),
        (102, 13),
        (103, 12),
        (104, 4)
;

INSERT INTO comments (comment, created_at)
    VALUES
        ('The darkroom process sounds so meditative. I''ve been wanting to try film photography for ages — what would you recommend for a complete beginner?', '2024-01-08 00:00:00+00'),
        ('Kodak Gold 200 is such a great starting point. The overexposed ones are honestly sometimes better anyway lol', '2024-01-08 00:00:00+00'),
        ('ok but the double exposure one sounds INCREDIBLE. please post the print when it''s done', '2024-01-17 00:00:00+00'),
        ('I did something similar once but on purpose and it never looked as good as the accidents do. there''s a lesson in there somewhere', '2024-01-17 00:00:00+00'),
        ('This is beautiful writing. The camera sees while the eye is busy looking — I''m going to think about that for a while.', '2024-03-21 00:00:00+00'),
        ('22 rolls!! the dedication. I could never be that patient waiting for scans', '2024-03-21 00:00:00+00'),
        ('lo-fi + rain is literally the only correct combination. add a weighted blanket and you have perfection', '2024-01-09 00:00:00+00'),
        ('same energy as me rn honestly', '2024-01-09 00:00:00+00'),
        ('Day 1 and I''m already stressed on your behalf lol. Please update us', '2024-01-10 00:00:00+00'),
        ('The commitment to making ramen from scratch is a personality trait and I respect it deeply', '2024-01-10 00:00:00+00'),
        ('I tried this once and my broth came out brown and thin. What am I doing wrong??', '2024-01-10 00:00:00+00'),
        ('you have to keep it at a ROLLING boil the whole time, not a simmer. that''s what makes it milky and rich', '2024-01-10 00:00:00+00'),
        ('Day 3 update DID NOT disappoint. Please write the full recipe eventually I''m begging', '2024-01-19 00:00:00+00'),
        ('your roommate''s reaction is exactly what good food deserves. silence first, then everything else', '2024-01-19 00:00:00+00'),
        ('I''ve been making tonkotsu for years and the kansui noodles from scratch is the part I always skip. respect.', '2024-01-19 00:00:00+00'),
        ('The passive house retrofit problem is so real and so underdiscussed. Every time I go to a green building conference it''s all shiny new construction and zero conversation about the existing stock.', '2024-01-11 00:00:00+00'),
        ('The Bronx project sounds amazing. Will you be sharing more details about the CLT specification at any point?', '2024-01-11 00:00:00+00'),
        ('Congrats!! I''m crying reading this. The thing about your mom 😭', '2024-01-12 00:00:00+00'),
        ('3:41 is INCREDIBLE for a first qualifier. You''re going to destroy Boston', '2024-01-12 00:00:00+00'),
        ('I ran Houston last year in 4:02 and thought I was going to die at mile 22. You are built differently.', '2024-01-12 00:00:00+00'),
        ('The humidity in January there is criminal. You earned every second of that time.', '2024-01-12 00:00:00+00'),
        ('okay i''ve read this three times and i still don''t know if I agree with you or if you''ve just argued it very convincingly', '2024-01-13 00:00:00+00'),
        ('The post-hoc narrative framing is the part that gets me. Like we decide and then we explain the decision to ourselves after the fact. Scary stuff.', '2024-01-13 00:00:00+00'),
        ('hard determinism always breaks down for me when I try to apply it to moral responsibility. how do you hold people accountable in that framework', '2024-01-13 00:00:00+00'),
        ('That''s actually a solid legal/philosophical question — compatibilist free will tries to square that circle if you want to go deeper', '2024-01-13 00:00:00+00'),
        ('CONGRATULATIONS!! Come celebrate soon, dinner is on me', '2024-01-14 00:00:00+00'),
        ('Going to be there Friday for sure. The arroz con pollo is the one I''m most excited about', '2024-01-14 00:00:00+00'),
        ('my monstera is dying and i''m choosing to not think about what that means', '2024-01-15 00:00:00+00'),
        ('what''s your light situation? mine turned around completely when I moved it closer to the window but out of direct sun', '2024-01-15 00:00:00+00'),
        ('The co-founder alignment point is the one nobody talks about enough. We were best friends. We should never have started a company together.', '2024-01-16 00:00:00+00'),
        ('Paying everyone out of pocket says everything about the kind of person you are.', '2024-01-16 00:00:00+00'),
        ('The ''early by three years'' thing haunts me. My first startup was the same story. The timing variable is brutal and mostly out of your hands.', '2024-01-16 00:00:00+00'),
        ('I needed to read the part about building something sustainable. We''ve been pressured to raise and I keep resisting and everyone thinks I''m crazy.', '2024-01-16 00:00:00+00'),
        ('You''re not crazy. Profitable and sustainable beats fast and fragile every time, at least for the humans involved.', '2024-01-16 00:00:00+00'),
        ('Fujifilm vs Kodak discourse is eternal and I love every iteration of it. I''m a Portra 400 loyalist myself but I respect your reasoning completely.', '2024-02-07 00:00:00+00'),
        ('The ''different moods'' framing is exactly right. It''s not about better or worse, it''s about what you''re trying to feel.', '2024-02-07 00:00:00+00'),
        ('okay what about Ilford HP5 in this framework where does that land', '2024-02-07 00:00:00+00'),
        ('HP5 is its own category entirely, it''s the film for when you want the world to feel a little bit heavier and more serious lol', '2024-02-07 00:00:00+00'),
        ('I felt this at 3am last night. Didn''t even have a reason. Just awake.', '2024-01-18 00:00:00+00'),
        ('the comma after ''sad'' is doing a lot of work in this post and I felt it', '2024-01-18 00:00:00+00'),
        ('The part about walking the same street multiple times is so true. I''ve shot the same block for two years and I''m still finding new things.', '2024-03-13 00:00:00+00'),
        ('Rule 3 should be the first rule honestly. No photo is worth making someone uncomfortable.', '2024-03-13 00:00:00+00'),
        ('The photo you almost didn''t take one is the reason I now shoot first and hesitate later. Changed how I work.', '2024-03-13 00:00:00+00'),
        ('Boston qualifier to Boston to Chicago PR in one year is an absolutely unhinged training arc in the best way', '2024-01-12 00:00:00+00'),
        ('I ugly cried reading the Boston post. 3:38 and a personal best?? You are AMAZING', '2024-04-15 00:00:00+00'),
        ('The Boylston Street stretch hits different when you''re in it. I did Boston in 2019 and I still get emotional thinking about it.', '2024-04-15 00:00:00+00'),
        ('Your mom was absolutely with you. No doubt.', '2024-04-15 00:00:00+00'),
        ('3:34 at Chicago is a full 4+ minute PR. You are not the same runner who qualified at Houston. This is incredible.', '2024-10-13 00:00:00+00'),
        ('The IT band will talk to you for a week and then shut up. Ice it. You''ve earned the complaining rights.', '2024-10-13 00:00:00+00'),
        ('The hippocampal replay stuff is genuinely fascinating. The idea that emotional tagging influences consolidation strength — do you know of any work linking this to trauma memory formation?', '2024-02-10 00:00:00+00'),
        ('That explains why I remember every embarrassing thing I''ve ever done with photographic clarity and forget where I put my phone every single day', '2024-02-10 00:00:00+00'),
        ('Good luck Friday!! I''ll be there', '2024-02-12 00:00:00+00'),
        ('Sold out in two hours on your FIRST day. That is not a coincidence, that''s years of work showing up.', '2024-01-23 00:00:00+00'),
        ('Your cousin burning herself twice and keeping going is the most beautiful thing I''ve read today', '2024-01-23 00:00:00+00'),
        ('The picadillo recipe!! I''ve been waiting for this since you opened. Making it this weekend.', '2024-01-31 00:00:00+00'),
        ('My abuela also never measured anything. I think that''s just how real cooking works.', '2024-01-31 00:00:00+00'),
        ('Adding the olives is non-negotiable. Anyone who leaves them out is wrong.', '2024-01-31 00:00:00+00'),
        ('What''s your take on raisins in picadillo? My family is divided on this every holiday.', '2024-01-31 00:00:00+00'),
        ('No raisins. This is not up for debate. Your abuela and my abuela are in agreement from the beyond.', '2024-01-31 00:00:00+00'),
        ('The oxtail selling out in 40 minutes is exactly what it deserved. Please make 80 next week.', '2024-03-14 00:00:00+00'),
        ('Valentina sounds like an absolute legend. Hold onto her.', '2024-02-19 00:00:00+00'),
        ('Good people AND fast learners are the rarest combination. You got lucky.', '2024-02-19 00:00:00+00'),
        ('The short rib taco being permanent is the best news I''ve heard all week and I mean that sincerely', '2024-03-25 00:00:00+00'),
        ('Thank you for naming the tension between growing and keeping the soul of the thing. Most food truck success stories skip that part.', '2024-11-15 00:00:00+00'),
        ('Tyler asking for hot chocolate after that whole conversation about fear is the most 9-year-old thing possible and I love it', '2024-01-25 00:00:00+00'),
        ('The sailing patience = leadership patience connection is something I''ve never heard articulated that way but it''s completely right.', '2024-04-04 00:00:00+00'),
        ('I grew up on the coast and this post made me homesick in a way I wasn''t expecting on a Tuesday morning.', '2024-04-04 00:00:00+00'),
        ('The Melian Dialogue is haunting me now. I read it in college and forgot how brutal it is.', '2024-02-05 00:00:00+00'),
        ('I''ve assigned Thucydides to students for 15 years and the Melian Dialogue never loses its impact. You''ve described it perfectly.', '2024-02-05 00:00:00+00'),
        ('The ospreys are back = spring is real. This is the only calendar system I trust.', '2024-03-17 00:00:00+00'),
        ('I read this and then went outside and stood in the sun for five minutes. Thank you.', '2024-03-17 00:00:00+00'),
        ('Tyler knowing every piece of hardware is the best thing. You''re raising a sailor.', '2024-11-21 00:00:00+00'),
        ('Reading this after a long week and it hit somewhere quiet. Thank you for writing it.', '2024-02-14 00:00:00+00'),
        ('41 years. I hope I get to write something like this someday.', '2024-04-06 00:00:00+00'),
        ('The chair detail broke me. I''m so sorry for your loss.', '2024-04-06 00:00:00+00'),
        ('logo revision 14 should be a war crime', '2024-01-26 00:00:00+00'),
        ('I once did 22 revisions for a startup that pivoted and never launched. 22. I still think about it.', '2024-01-26 00:00:00+00'),
        ('the ''we''ll know it when we see it'' clients are the ones who don''t know what they want AND don''t trust you to figure it out for them. nightmare combination.', '2024-01-26 00:00:00+00'),
        ('logo revision 21 being approved made me physically exhale. I''ve been invested in this saga', '2024-02-25 00:00:00+00'),
        ('The typography post is everything. The number of fintech apps I''ve had to design for that insist on Inter and nothing else is too high.', '2024-03-05 00:00:00+00'),
        ('A custom lettering wordmark for a bakery sounds BEAUTIFUL. Any chance you''d share it?', '2024-03-05 00:00:00+00'),
        ('finished a sketchbook completely is genuinely a milestone. I have eight half-finished ones on my shelf judging me.', '2024-11-20 00:00:00+00'),
        ('The progression from first page to last is always the most honest portfolio you''ll ever have.', '2024-11-20 00:00:00+00'),
        ('the five things I believe list is going on my studio wall. especially number 2.', '2024-04-21 00:00:00+00'),
        ('Number 4 is the uncomfortable one. Taste taking longer than any school tells you is so true and nobody warns you.', '2024-04-21 00:00:00+00'),
        ('The Hasselblad for $800 is a crime that you benefited from. Congrats. That camera is going to ruin your other cameras for you.', '2024-07-15 00:00:00+00'),
        ('Medium format is a trap because once you see the quality you can''t unsee it. Welcome to the expensive side.', '2024-07-15 00:00:00+00'),
        ('The plant is thriving and that''s the only update I needed today', '2024-01-15 00:00:00+00'),
        ('three emojis as a bio is the most unbothered energy possible. I respect it.', '2024-01-30 00:00:00+00'),
        ('denver really does go hard with the winter sun. people in other states look at me like I''m lying when I describe January there', '2024-01-30 00:00:00+00'),
        ('live music does something no recording can replicate. it''s the shared physical presence of it. glad you went.', '2024-03-18 00:00:00+00'),
        ('I went to a show last month after a really hard week and it fixed something in me I didn''t know was broken', '2024-03-18 00:00:00+00'),
        ('the ''performing productivity'' thing is so real it''s uncomfortable. I''ve had 45-minute days inside 8-hour ones and nobody noticed.', '2024-01-24 00:00:00+00'),
        ('Honestly the 40 minutes of real work probably produce more than most people''s 8 hours anyway', '2024-01-24 00:00:00+00'),
        ('the brain at 2am sending you random trivia questions is a universal experience I think', '2024-02-03 00:00:00+00'),
        ('I once spent 45 minutes at 3am researching whether hot dogs are sandwiches. The internet is a dangerous place at night.', '2024-02-03 00:00:00+00'),
        ('the ''just awake'' feeling is so specific and so isolating. hope you got some sleep eventually', '2024-01-18 00:00:00+00'),
        ('Rewiring a bathroom fixture is where it starts. Next thing you know you''re replacing subfloor at midnight. Respect the journey.', '2024-02-01 00:00:00+00'),
        ('This is why YouTube is the most useful website ever created, unpopular opinion but I stand by it', '2024-02-01 00:00:00+00'),
        ('The thesis advisor communication scale is painfully accurate. ''Making progress'' meaning ''fine'' is the most compressed emotional vocabulary ever developed.', '2024-01-29 00:00:00+00'),
        ('My advisor communicates entirely in long silences and single raised eyebrows. I envy you your three modes.', '2024-01-29 00:00:00+00'),
        ('The imposter syndrome never going away thing is the most discouraging encouragement I''ve ever received, and also somehow helpful?', '2024-03-15 00:00:00+00'),
        ('Six years in and it still hits? That''s somehow reassuring and devastating at the same time. Thank you for being honest about it.', '2024-03-15 00:00:00+00'),
        ('CONGRATULATIONS on the acceptance!! Journal of Neuroscience is not small. This is huge.', '2024-04-01 00:00:00+00'),
        ('First first-author paper at JNeurosci is a massive deal. Your advisor saying ''I told you so'' is chef''s kiss.', '2024-04-01 00:00:00+00'),
        ('The Copenhagen lab collaboration sounds incredible. Parallel experiments across two continents is big science energy.', '2024-11-01 00:00:00+00'),
        ('UCL is a great group for hippocampal work. You''re going to learn so much from that collaboration.', '2024-11-01 00:00:00+00'),
        ('The presenter who goes into flow state mid-talk and stops being nervous — that''s the dream. Sounds like it went really well.', '2024-03-23 00:00:00+00'),
        ('The professor who asks the supplementary materials question in person is a special kind of person. Glad you were ready for him.', '2024-03-23 00:00:00+00'),
        ('Sourdough Dutch oven is the only correct method and I will die on this hill. Congrats on the successful loaf.', '2024-02-26 00:00:00+00'),
        ('The crust shattering when you tap it is the most satisfying sound in all of baking. You did it.', '2024-02-26 00:00:00+00'),
        ('The miso post after nine months of waiting is so quietly triumphant. This is the most patient cooking post I''ve ever read.', '2024-12-11 00:00:00+00'),
        ('Nine months to make, ten minutes to use, and it was worth every day. That''s a whole philosophy of life right there.', '2024-12-11 00:00:00+00'),
        ('The survivorship bias point is the most important thing in this post and it''s buried in the middle. The failure post-mortems are where the real education is.', '2024-02-08 00:00:00+00'),
        ('I''ve started specifically seeking out failure stories after reading stuff like this. They''re harder to find because nobody wants to write them.', '2024-02-08 00:00:00+00'),
        ('Profitable and turning down term sheets is genuinely rare. I have so many questions about how you''ve managed the growth without outside capital.', '2024-02-21 00:00:00+00'),
        ('The remote culture point about proximity masking weak culture is the most honest thing I''ve read about the return-to-office debate.', '2024-03-22 00:00:00+00'),
        ('We went full remote in 2020 and never went back and our culture is stronger than it was in-office. It''s about intentionality, exactly as you said.', '2024-03-22 00:00:00+00'),
        ('Coriander rattling the cabinet with pure determination is the most relatable character in any story I''ve read this year.', '2024-10-14 00:00:00+00'),
        ('The direct eye contact while knocking the mug off is cats asserting dominance and there''s nothing you can do about it. Welcome to having a cat.', '2024-10-14 00:00:00+00'),
        ('this is enough is the most grounding two-sentence post I''ve seen in a long time. saving this.', '2024-11-02 00:00:00+00'),
        ('The small apartment thesis is something I''ve been arguing with my partner about for years. 540 sqft sounds perfect to me.', '2024-03-20 00:00:00+00'),
        ('designing for people who''ll never know you exist and making their lives quietly better — that''s one of the most beautiful descriptions of a job I''ve ever read', '2024-02-02 00:00:00+00'),
        ('The texture of cities paragraph made me want to walk around my own city and actually feel it instead of just moving through it', '2024-02-28 00:00:00+00'),
        ('Milan vs New York is such a good comparison because they''re both genuinely beautiful and completely opposite in their logic.', '2024-02-28 00:00:00+00'),
        ('taper madness is a real clinical condition and I say this as someone who has been there seven times. the weather-checking is the worst symptom.', '2024-03-19 00:00:00+00'),
        ('55 and partly cloudy is basically perfect marathon weather. Your legs know what to do.', '2024-03-19 00:00:00+00'),
        ('The negative splits in snow story is unhinged running behavior and I mean that as the highest compliment.', '2024-02-04 00:00:00+00'),
        ('I did a half marathon once and you could not have paid me to run 10 miles in snow. You are built from different material.', '2024-02-04 00:00:00+00'),
        ('The Murakami quote and then ''crossing that line with 30,000 people doing the same lonely thing'' — you should write a book honestly', '2024-03-27 00:00:00+00')
;

INSERT INTO post_comment (post_id, comment_id)
    VALUES
        (1, 1),
        (1, 2),
        (10, 3),
        (10, 4),
        (73, 5),
        (73, 6),
        (2, 7),
        (2, 8),
        (3, 9),
        (3, 10),
        (3, 11),
        (3, 12),
        (12, 13),
        (12, 14),
        (12, 15),
        (4, 16),
        (4, 17),
        (5, 18),
        (5, 19),
        (5, 20),
        (5, 21),
        (6, 22),
        (6, 23),
        (6, 24),
        (6, 25),
        (7, 26),
        (7, 27),
        (8, 28),
        (8, 29),
        (9, 30),
        (9, 31),
        (9, 32),
        (9, 33),
        (9, 34),
        (31, 35),
        (31, 36),
        (31, 37),
        (31, 38),
        (11, 39),
        (11, 40),
        (65, 41),
        (65, 42),
        (65, 43),
        (5, 44),
        (76, 45),
        (76, 46),
        (76, 47),
        (97, 48),
        (97, 49),
        (34, 50),
        (34, 51),
        (36, 52),
        (16, 53),
        (16, 54),
        (24, 55),
        (24, 56),
        (24, 57),
        (24, 58),
        (24, 59),
        (66, 60),
        (43, 61),
        (43, 62),
        (79, 63),
        (101, 64),
        (18, 65),
        (87, 66),
        (87, 67),
        (29, 68),
        (29, 69),
        (69, 70),
        (69, 71),
        (103, 72),
        (38, 73),
        (91, 74),
        (91, 75),
        (19, 76),
        (19, 77),
        (19, 78),
        (49, 79),
        (57, 80),
        (57, 81),
        (102, 82),
        (102, 83),
        (96, 84),
        (96, 85),
        (94, 86),
        (94, 87),
        (8, 88),
        (23, 89),
        (23, 90),
        (70, 91),
        (70, 92),
        (17, 93),
        (17, 94),
        (27, 95),
        (27, 96),
        (11, 97),
        (25, 98),
        (25, 99),
        (22, 100),
        (22, 101),
        (67, 102),
        (67, 103),
        (84, 104),
        (84, 105),
        (99, 106),
        (99, 107),
        (75, 108),
        (75, 109),
        (50, 110),
        (50, 111),
        (89, 112),
        (89, 113),
        (32, 114),
        (32, 115),
        (45, 116),
        (74, 117),
        (74, 118),
        (98, 119),
        (98, 120),
        (100, 121),
        (72, 122),
        (26, 123),
        (52, 124),
        (52, 125),
        (71, 126),
        (71, 127),
        (28, 128),
        (28, 129),
        (81, 130)
;

INSERT INTO comment_user (comment_id, user_id)
    VALUES
        (1, 3),
        (2, 10),
        (3, 13),
        (4, 12),
        (5, 7),
        (6, 6),
        (7, 11),
        (8, 4),
        (9, 5),
        (10, 14),
        (11, 8),
        (12, 1),
        (13, 2),
        (14, 10),
        (15, 5),
        (16, 14),
        (17, 7),
        (18, 10),
        (19, 14),
        (20, 2),
        (21, 9),
        (22, 4),
        (23, 3),
        (24, 8),
        (25, 9),
        (26, 13),
        (27, 7),
        (28, 6),
        (29, 1),
        (30, 13),
        (31, 7),
        (32, 1),
        (33, 3),
        (34, 5),
        (35, 9),
        (36, 6),
        (37, 2),
        (38, 1),
        (39, 6),
        (40, 13),
        (41, 10),
        (42, 14),
        (43, 3),
        (44, 5),
        (45, 13),
        (46, 12),
        (47, 3),
        (48, 10),
        (49, 9),
        (50, 5),
        (51, 4),
        (52, 2),
        (53, 14),
        (54, 1),
        (55, 2),
        (56, 7),
        (57, 5),
        (58, 8),
        (59, 9),
        (60, 1),
        (61, 9),
        (62, 14),
        (63, 7),
        (64, 9),
        (65, 11),
        (66, 5),
        (67, 13),
        (68, 3),
        (69, 12),
        (70, 4),
        (71, 11),
        (72, 1),
        (73, 6),
        (74, 5),
        (75, 3),
        (76, 9),
        (77, 3),
        (78, 14),
        (79, 7),
        (80, 9),
        (81, 1),
        (82, 5),
        (83, 10),
        (84, 6),
        (85, 3),
        (86, 7),
        (87, 13),
        (88, 14),
        (89, 10),
        (90, 1),
        (91, 6),
        (92, 4),
        (93, 8),
        (94, 2),
        (95, 6),
        (96, 2),
        (97, 5),
        (98, 13),
        (99, 4),
        (100, 8),
        (101, 2),
        (102, 7),
        (103, 10),
        (104, 14),
        (105, 5),
        (106, 12),
        (107, 3),
        (108, 10),
        (109, 12),
        (110, 7),
        (111, 1),
        (112, 5),
        (113, 14),
        (114, 9),
        (115, 13),
        (116, 3),
        (117, 7),
        (118, 5),
        (119, 1),
        (120, 12),
        (121, 6),
        (122, 10),
        (123, 9),
        (124, 1),
        (125, 14),
        (126, 7),
        (127, 3),
        (128, 5),
        (129, 2),
        (130, 13)
;
`;

module.exports = {
    createTablesSQL,
    insertToTablesSQL,
};
